---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# ropenlabs

<!-- badges: start -->
<!-- badges: end -->

A code and link repository supporting the [R Open Labs workshop series](https://rfun.library.duke.edu/portfolio/r_open_labs/), sponsored by the [Center for Data & Visualization Sciences](https://library.duke.edu/data/)

## Master the Tidyverse
https://github.com/rstudio/master-the-tidyverse

- 01 Introduction
- 02 Visualize Data 
- 03 Transform Data
- 04 Tidy Data
- 05 Iteration
- 06 Models

## Resources

-  [Master the Tidyverse](https://github.com/rstudio/master-the-tidyverse) 
-  the RStudio interactive [R Primers](https://rstudio.cloud/learn/primers)
-  [*R for Data Science*](https://r4ds.had.co.nz/) by Hadley Wickham & Garrett Grolemund (select chapters, workbook - Problems, and solutions)
-  [ggplot2](https://ggplot2-book.org/) visualization for data analysis by Hadley Wickham
-  the interactive dataquest.io [learning series on R](https://www.dataquest.io/path/data-analyst-r/)
-  [*Advanced R*](https://adv-r.hadley.nz/) by Hadley Wickham (select chapters and workbook problems)

## Rfun

- https://rfun.library.duke.edu
- https://rfun.library.duke.edu/portfolio/r_open_labs

## Networking Groups
- ROpenLabs:  https://rfun.library.duke.edu/portfolio/r_open_labs
- Slack:  https://ropenlabs.slack.com
- Sympa List:  https://lists.duke.edu/sympa/info/ropenlabs
- RTP Ladies:  https://www.meetup.com/rladies-rtp/events/

## R Markdown, Dashboards & Slides
Start with the [slides and dashboards](sessions/99_slides_dashboards.md) document